
     (letrec ((LOOP10 (lambda (universe1 b-folder1 foo0 bar0 accross0)
                        (let ((first0 (($$atom car) ($$atom universe1))))
                          (begin
                            (($$atom cdr) ($$atom universe1))
                            (($$atom b-folder1)
                             ($$atom first0)
                             ($$atom bar0)
                             (lambda ()
                               (($$atom LOOP10)
                                ($$atom universe1)
                                ($$atom b-folder1)))
                             ($$atom 11)))))))
       (($$atom LOOP10)
        ($$atom '(1))
        (lambda (a0 b0 c0 d0) ($$atom 11))
        ($$atom 12)
        ($$atom 1)
        ($$atom 11)))
