
(pp (char=? #\A #\B))
(pp (char=? #\A #\A))
(pp (char=? #\B #\A))
(pp (char<? #\A #\B))
(pp (char<? #\A #\A))
(pp (char<? #\B #\A))
(pp (char>? #\A #\B))
(pp (char>? #\A #\A))
(pp (char>? #\B #\A))
(pp (char<=? #\A #\B))
(pp (char<=? #\A #\A))
(pp (char<=? #\B #\A))
(pp (char>=? #\A #\B))
(pp (char>=? #\A #\A))
(pp (char>=? #\B #\A))

(pp 1234567890)

(pp (char=? #\a #\b))
(pp (char=? #\a #\a))
(pp (char=? #\b #\a))
(pp (char<? #\a #\b))
(pp (char<? #\a #\a))
(pp (char<? #\b #\a))
(pp (char>? #\a #\b))
(pp (char>? #\a #\a))
(pp (char>? #\b #\a))
(pp (char<=? #\a #\b))
(pp (char<=? #\a #\a))
(pp (char<=? #\b #\a))
(pp (char>=? #\a #\b))
(pp (char>=? #\a #\a))
(pp (char>=? #\b #\a))

(pp 1234567890)

(pp (char<? #\0 #\9))
(pp (char<? #\5 #\5))
(pp (char<? #\9 #\0))
(pp (char>? #\0 #\9))
(pp (char>? #\5 #\5))
(pp (char>? #\9 #\0))
(pp (char<=? #\0 #\9))
(pp (char<=? #\5 #\5))
(pp (char<=? #\9 #\0))
(pp (char>=? #\0 #\9))
(pp (char>=? #\5 #\5))
(pp (char>=? #\9 #\0))

(pp 1234567890)

(pp (char=? #\a #\1))
(pp (char=? #\A #\1))
(pp (char=? #\1 #\a))
(pp (char=? #\1 #\A))
(pp (char=? #\a #\A))
(pp (char=? #\A #\a))
(pp (char<? #\a #\1))
(pp (char<? #\A #\1))
(pp (char<? #\1 #\a))
(pp (char<? #\1 #\A))
(pp (char<? #\a #\A))
(pp (char<? #\A #\a))
(pp (char>? #\a #\1))
(pp (char>? #\A #\1))
(pp (char>? #\1 #\a))
(pp (char>? #\1 #\A))
(pp (char>? #\a #\A))
(pp (char>? #\A #\a))
(pp (char<=? #\a #\1))
(pp (char<=? #\A #\1))
(pp (char<=? #\1 #\a))
(pp (char<=? #\1 #\A))
(pp (char<=? #\a #\A))
(pp (char<=? #\A #\a))
(pp (char>=? #\a #\1))
(pp (char>=? #\A #\1))
(pp (char>=? #\1 #\a))
(pp (char>=? #\1 #\A))
(pp (char>=? #\a #\A))
(pp (char>=? #\A #\a))

(pp 1234567890)

(pp (char-alphabetic? #\`))
(pp (char-alphabetic? #\a))
(pp (char-alphabetic? #\s))
(pp (char-alphabetic? #\z))
(pp (char-alphabetic? #\{))
(pp (char-alphabetic? #\@))
(pp (char-alphabetic? #\A))
(pp (char-alphabetic? #\S))
(pp (char-alphabetic? #\Z))
(pp (char-alphabetic? #\[))
(pp (char-alphabetic? #\_))
(pp (char-alphabetic? #\5))

(pp 1234567890)

(pp (char-numeric? #\/))
(pp (char-numeric? #\0))
(pp (char-numeric? #\5))
(pp (char-numeric? #\9))
(pp (char-numeric? #\:))
(pp (char-numeric? #\e))
(pp (char-numeric? #\E))
(pp (char-numeric? #\+))

(pp 1234567890)

(pp (char-whitespace? #\a))
(pp (char-whitespace? #\6))
(pp (char-whitespace? #\A))
(pp (char-whitespace? #\+))
(pp (char-whitespace? #\{))
(pp (char-whitespace? #\space))
(pp (char-whitespace? #\tab))
(pp (char-whitespace? #\newline))
(pp (char-whitespace? #\page))
(pp (char-whitespace? #\return))

(pp 1234567890)

(pp (char-upper-case? #\a))
(pp (char-upper-case? #\6))
(pp (char-upper-case? #\{))
(pp (char-upper-case? #\*))
(pp (char-upper-case? #\return))
(pp (char-upper-case? #\A))
(pp (char-upper-case? #\S))
(pp (char-upper-case? #\Z))
(pp (char-upper-case? #\@))
(pp (char-upper-case? #\[))

(pp 1234567890)

(pp (char-lower-case? #\A))
(pp (char-lower-case? #\6))
(pp (char-lower-case? #\{))
(pp (char-lower-case? #\*))
(pp (char-lower-case? #\return))
(pp (char-lower-case? #\a))
(pp (char-lower-case? #\s))
(pp (char-lower-case? #\z))
(pp (char-lower-case? #\`))
(pp (char-lower-case? #\{))